version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: toilet
      POSTGRES_PASSWORD: toilet
      POSTGRES_DB: toilet_db
    volumes:
      - pgdata:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: toilet
      DB_PASSWORD: toilet
      DB_NAME: toilet_db

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8080

volumes:
  pgdata:
