version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: toilet
      POSTGRES_PASSWORD: toilet
      POSTGRES_DB: toilet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend/migrations:/app/migrations
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: toilet
      DB_PASSWORD: toilet

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    environment:
      VITE_API_URL: http://backend:8080

  nginx:
    image: nginx:latest
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
